### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by klaussilveira** [koerismo/PBR-2-Source#10]
Here's how the configuration is set:
![image](https://github.com/user-attachments/assets/fbfc5226-f684-43f8-a380-e9578b8be333)

Output:
```
Albedo icon updated!
Roughness icon updated!
Metallic icon updated!
Normal icon updated!
Ao icon updated!
Emit icon updated!
Exporting...
Constructing material...
Picking target
Export: Processing textures...
PBR-2-Source/src/module/core/io/image.py:169: RuntimeWarning: divide by zero encountered in power
  self.data **= other
PBR-2-Source/src/module/core/io/image.py:169: RuntimeWarning: overflow encountered in power
  self.data **= other
Export: Making VMT...
Export: Writing files...
Export: Finished exporting exported.vmt!
```

Exported maps are all off:
![image](https://github.com/user-attachments/assets/b40643ef-1005-400b-9cf4-20b0553ae109)

These are the source textures I've used:
https://user.fm/files/v2-06db7d2cb6769612004c156dddf6316c/material.zip

**Comment by koerismo** [comment]
Hi, thanks for the detailed report! Whenever this happens (which it will in some cases), it clamps the results, so it shouldn't be the cause of any issues.

I am seeing that it's misinterpreting the colorspace of some of your images, though. Have you tried exporting the textures as linear? The thumbnails should ideally match what you see in the default photo viewer.

**Comment by klaussilveira** [comment]
They are originally DDS textures, so I've used Imagick's `convert example.dds -set colorspace RGB example.png`. I still have the errors, but if I do `convert result.png -alpha off no_alpha.png`, the albedo and normal look almost correct:

![image](https://github.com/user-attachments/assets/4bfce85a-a848-4672-ad8a-29cdaf5c1534)

I wonder if this could be an issue with `vtex2`? I'm using it to convert the VTF back to a PNG.

**Comment by koerismo** [comment]
The alpha is used to store phong and envmap information, so the semitransparent output is actually correct. Why convert it back to a png? The vtfs should be readily usable via the generated vmt. (If they aren't, that's a bug.)

**Comment by klaussilveira** [comment]
Oh, I am not using Source 2, that's why. Porting PBR textures to DiffSpecNorm from Quake engines. This tool is incredibly helpful, specially for projects using rend2, like ET: Legacy, [OpenJK](https://jkhub.org/forums/topic/7468-rend2-a-modern-renderer/), [IORTCW](https://github.com/iortcw/iortcw/blob/master/rend2-readme.md), [ioquake3](https://github.com/ioquake/ioq3/blob/main/opengl2-readme.md), etc.
