### ISSUE TITLE
"Specified module could not be found"

### ISSUE THREAD

**Issue by TheNameNoOneKnew** [koerismo/PBR-2-Source#11]
Hello, i've recently had the need to use the tool you have developed as i am working on a tf2 skin mod, but for some reason none of the 2.0.0 and above builds work on my computer, they throw this error at me when i launch the executable (image attached below), 0.0.4 and below builds do work but they do not give me the desired results.
![Specified module could not be found](https://github.com/user-attachments/assets/0c2fc7ab-cf59-44c0-8915-dcd8fcca4774)
The text in spanish reads: "the specified module could not be found"

I hope this isn't caused by me using windows 8.1, but if it is just let me know, thank you.

**Comment by TheNameNoOneKnew** [comment]
I do have python installed btw

**Comment by koerismo** [comment]
Hi! I believe this is due to the Qt framework, which is used for the interface of this program, dropping support for Windows 8 and prior. There's not too much I can do about this without downgrading to Qt 5.X, unfortunately.
