### ISSUE TITLE
The basecolor texture ends up being absolutely black no matter what

### ISSUE THREAD

**Issue by romario516** [koerismo/PBR-2-Source#2]
The title is self explanatory
version is v0.0.4-alpha

**Comment by koerismo** [comment]
Sorry about that! This is an issue with algorithms that the current version uses. I'm currently working on rewriting PBR-2-Source from the ground up, and this will be resolved in the next version.

I can't give an ETA on when it will be finished as I am busy with P2:CE, but the (obviously work-in-progress) CLI can be found on the experimental rewrite-2 branch. It should already produce much more accurate results.

**Comment by Baklojan** [comment]
really hope its getting worked on
build.bat in [rewrite 2] is outdated and im python tools hater
