### ISSUE TITLE
Failed to find materials directory

### ISSUE THREAD

**Issue by radiationwow** [koerismo/PBR-2-Source#3]
I'm getting error "Failed to find materials directory! Be sure that you are exporting into a content folder."

I've tried changing the folders million times, tried different drives, tried running as admin and it always gives me this error. 

here's my folder structure if that helps

material folder : F:\Sourceproject\models\glockbase
export folder : F:\Sourceproject\models\glockbase\source_export

What does content folder even mean? Is it the folder of the materials? I've tried that as export folder too, but no success.

**Comment by koerismo** [comment]
Hi! Make sure you're exporting to the `Sourceproject\materials\models\...` directory instead of the `Sourceproject\models\...` directory.
